'use client';
import { Provider } from 'react-redux';
import store from '../store/store';
// import type { Metadata } from "next";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
         {children}
         </Provider>
      </body>
    </html>
  );
}
